[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm ci --omit=dev",
  "npm remove @shopify/cli || true"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "sh -c 'npx prisma migrate deploy && npm run docker-start'"

[variables]
NODE_ENV = "production"
