# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "665dc5bbd35756bbd2d8a4f26f77b174"
name = "shxhid-production-mcp"
application_url = "https://shxhid-chat-agent-production.up.railway.app"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "read_products,customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings,unauthenticated_read_product_inventory,unauthenticated_read_product_pickup_locations,unauthenticated_write_checkouts,unauthenticated_read_checkouts,unauthenticated_write_customers,unauthenticated_read_customers,unauthenticated_read_customer_tags,unauthenticated_read_content,unauthenticated_read_selling_plans,unauthenticated_read_product_tags"

[auth]
redirect_urls = [ "https://shxhid-chat-agent-production.up.railway.app/auth/callback" ]

[pos]
embedded = false

[customer_authentication]
redirect_uris = [
  "https://shxhid-chat-agent-production.up.railway.app/auth/callback"
]

[app_proxy]
url = "https://shxhid-chat-agent-production.up.railway.app"
subpath = "shop-chat"
prefix = "apps"
