# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "448a66ca9b4cbb16ded22cddef5b1610"
name = "shxhid"
application_url = "https://shxhid-chat-agent-production.up.railway.app"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://shop-chat-agent.com/api/auth" ]

[pos]
embedded = false

[customer_authentication]
redirect_uris = [
  "https://shop-chat-agent.com/callback"
]
